services:
  - type: web
    name: my-habits
    runtime: static
    buildCommand: node build-config.js
    staticPublishPath: .
    envVars:
      - key: JSONBIN_API_KEY
        sync: false
      - key: JSONBIN_BIN_ID
        sync: false
